---

project_directories:  
    - "./#{name.capitalize}"
    - "./#{name.capitalize}/public"
    - "./#{name.capitalize}/public/images"
    - "./#{name.capitalize}/public/javascripts"
    - "./#{name.capitalize}/public/stylesheets"
    - "./#{name.capitalize}/views" 

files: 
    - "#{name.capitalize}.rb"
    - Gemfile
    - README.md
    - config.ru

main_file:
    - "$:.unshift File.expand_path('../lib', __FILE__)\n"
    - "require 'sinatra/base'\n"
    - "\nclass #{name.capitalize} < Sinatra:Base\n"
    - "\nend"

gems:
    - "source 'https://rubygems.org'\n"
    - "\ngem 'sinatra'"
    - "\ngem 'rubocop'"
    - "\ngem 'puma'\n"
    - "\ngroup :test do"
    - "\n  gem 'rack-test'"
    - "\n  gem 'rspec'"
    - "\nend"

readme:
    - "## #{name.capitalize}"

config_ru:
    - "require './#{name.capitalize}'\n"
    - "\nrun #{name.capitalize}.new"
